### ISSUE TITLE
[Bug?] Sqlite dependancy not found under Linux

### ISSUE THREAD

**Issue by mgurzixo** [caoxiemeihao/electron-vite-vue#76]
Hello,

When using the pristine template under Linux, `npm run dev` works perfectly, but building for Linux and running the . snap gives a black window with a spinning logo. When activating the dev tools, The console says: 

> Uncaught Error: Cannot find module 'node-pre-gyp
> Require stack:
> - /home/mgouget/dev/electron-vue-vite/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js
> - /home/mgouget/dev/electron-vue-vite/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js
> - /home/mgouget/dev/electron-vue-vite/release/1.0.0/linux-unpacked/resources/app.asar/dist/renderer/index.html
>     at Module._resolveFilename (node:internal/modules/cjs/loader:940)
>     at Function.o._resolveFilename (node:electron/js2c/renderer_init:33)
>     at Module._load (node:internal/modules/cjs/loader:785)
>     at Function.c._load (node:electron/js2c/asar_bundle:5)
>     at Function.o._load (node:electron/js2c/renderer_init:33)
>     at Module.require (node:internal/modules/cjs/loader:1012)
>     at require (node:internal/modules/cjs/helpers:94)
>     at Object.<anonymous> (/home/mgouget/dev/electron-vue-vite/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:1)
>     at Object.<anonymous> (/home/mgouget/dev/electron-vue-vite/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:7)
>     at Module._compile (node:internal/modules/cjs/loader:1116)`

The same thing occurs when launching directly `release/1.0.0/linux-unpacked/electron-vue-vite`.

When listing the `release/1.0.0/linux-unpacked/resources/app.asar` archive  with the `asar` CLI, we see that `node-gyp` and `node-pre-gyp` are not inside, but do exist in `node_modules/sqlite3/node_modules/.bin`.

I suspect that the content of the `.bin` directory is not added by `electron-builder` because the name starts with a dot.

When commenting out the `sqliteExample` 2 lines in `src/main.ts`, everything works OK.

My environment:

-  Linux Ubuntu 21.10 (impish)
-  Electron 16.0.8
- Electron-builder 22.14.5
- Sqlite3: 5.0.2

Any idea or suggestion?

Cheers,
Michel

**Comment by caoxiemeihao** [comment]
You can try this template, maybe can help you  
[electron-vite-boilerplate](https://github.com/caoxiemeihao/electron-vite-boilerplate)

**Comment by mgurzixo** [comment]
Thank you caoxiemeihao for your quick answer.

Running it causes the same results: OK in dev mode, error after running the build.

Have you tested your template under Linux?

 Just to see, I commented out the `sqlite3` part, and got the same result with `serialport`. Again, just to see, I started adding as dependencies of the project the names that popped up. After having added:

```
"dependencies": {
    "@serialport/binding-mock": "^10.2.2",
    "@serialport/bindings-cpp": "^10.7.0",
    "@serialport/bindings-interface": "^1.2.1",
    "@serialport/parser-byte-length": "^10.3.0",
    "@serialport/parser-cctalk": "^10.3.0",
    "@serialport/parser-delimiter": "^10.3.0",
    "@serialport/parser-inter-byte-timeout": "^10.3.0",
    "@serialport/parser-packet-length": "^10.3.0",
    "@serialport/parser-readline": "^10.3.0",
    "@serialport/parser-ready": "^10.3.0",
    "@serialport/parser-regex": "^10.3.0",
    "@serialport/parser-slip-encoder": "^10.3.0",
    "@serialport/parser-spacepacket": "^10.3.0",
    "@serialport/stream": "^10.3.0",
    "abbrev": "^1.1.1",
    "are-we-there-yet": "^3.0.0",
    "console-control-strings": "^1.1.0",
    "core-util-is": "^1.0.3",
    "debug": "^4.3.4",
    "delegates": "^1.0.0",
    "fstream": "^1.0.12",
    "gauge": "^4.0.3",
    "glob": "^7.2.0",
    "graceful-fs": "^4.2.9",
    "inherits": "^2.0.4",
    "isarray": "^2.0.5",
    "isexe": "^2.0.0",
    "mkdirp": "^1.0.4",
    "ms": "^2.1.3",
```
in `package.json`, the thing worked OK with only `serialport`.

I tried to do the same for `sqlite3`, but got finally the runtime error:
```
Uncaught Error: require() of ES Module /home/xxx/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/string-width/index.js from /home/xxx/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/wide-align/align.js not supported.
Instead change the require of index.js in /home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1144:19)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.o._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/wide-align/align.js:2:19)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/wide-align/align.js:67:3)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.o._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/gauge/lib/render-template.js:2:13)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/gauge/lib/render-template.js:224:3)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.o._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/gauge/lib/plumbing.js:3:22)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/gauge/lib/plumbing.js:52:3)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.o._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/gauge/lib/index.js:2:16)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/gauge/lib/index.js:292:3)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.o._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/npmlog/lib/log.js:3:13)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/npmlog/lib/log.js:406:3)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.o._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/node-pre-gyp/lib/node-pre-gyp.js:16:11)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/node-pre-gyp/lib/node-pre-gyp.js:205:3)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.o._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:1:169)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.o._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:2:15)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:207:3)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.o._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/dist/renderer/vendor.7134fd1c.js:1:175)
    at Object.<anonymous> (/home/mgouget/dev/electron-vite-boilerplate/release/1.0.0/linux-unpacked/resources/app.asar/dist/renderer/vendor.7134fd1c.js:3:3)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.o._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at index.16f48eb0.js:1:60
```
So I throw away the towel ;)

It looks like at least the dependencies of the native modules are not bundled in the `asar` archive.

Anyway, for my use case, I do not need native modules, so your template is perfect for me, thank you!

Michel

**Comment by caoxiemeihao** [comment]
Unfortunately, I only have one MAC now 😅  
In this template, SQLite3 is an experimental module  
Thank you for your feedback. I'm considering deleting it; Make this template simpler

**Comment by caoxiemeihao** [comment]
SQLite3 has been remove the templte.  
More example of case you can see [electron-vite-boilerplate](https://github.com/caoxiemeihao/electron-vite-boilerplate)
